apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Замінили 'accessMode' на 'accessModes' і додали тире
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-path"
