executor: CeleryExecutor

redis:
  enabled: true

flower:
  enabled: true

dags:
  gitSync:
    enabled: true
    repo: https://github.com/CtrlPy/airflow-kubernetes-example.git
    branch: main
    subPath: dags
    wait: 20  # Synchronization interval in seconds

webserver:
  service:
    type: ClusterIP  # Ми використовуємо ClusterIP через Ingress

ingress:
  enabled: true
  web:
    hosts:
      - airflow.local
    tls:  # Вимикаємо TLS для веб-сервера
      enabled: false
  flower:
    hosts:
      - flower.airflow.local
    tls:  # Вимикаємо TLS для Flower
      enabled: false

users:
  - username: admin
    password: admin  
    role: Admin

workers:
  persistence:
    enabled: true  # Включаємо персистентне зберігання логів
    size: 10Gi  # Встановлюємо розмір для сховища логів
  env:
    - name: AIRFLOW__LOGGING__BASE_LOG_FOLDER
      value: /opt/airflow/logs  # Вказуємо шлях для збереження логів
  extraVolumeMounts:
    - name: data-storage
      mountPath: /opt/airflow/storage
  extraVolumes:
    - name: data-storage
      persistentVolumeClaim:
        claimName: data-storage-pvc

  # Додаємо налаштування для KEDA
  keda:
    enabled: true
    pollingInterval: 5  # Частота перевірки запитів KEDA
    minReplicaCount: 1  # Мінімальна кількість воркерів
    maxReplicaCount: 10  # Максимальна кількість воркерів

persistence:
  dataStorage:
    enabled: true
    existingClaim: ""
    storageClass: "standard"  # Замініть на ваш клас сховища
    accessMode: ReadWriteMany
    size: 10Gi
    annotations: {}
    labels: {}
