executor: CeleryExecutor

redis:
  enabled: true

flower:
  enabled: true

dags:
  gitSync:
    enabled: true
    repo: https://github.com/CtrlPy/airflow-kubernetes-example.git
    branch: main
    subPath: dags
    wait: 20  # Synchronization interval in seconds

webserver:
  service:
    type: ClusterIP  # We use ClusterIP because we will use Ingress

ingress:
  enabled: true
  web:
    hosts:
      - airflow.local
    annotations:
      kubernetes.io/ingress.class: traefik
  flower:
    hosts:
      - flower.airflow.local
    annotations:
      kubernetes.io/ingress.class: traefik

  # If using TLS, uncomment and configure the following block
  # tls:
  #   - hosts:
  #       - airflow.local
  #     secretName: airflow-tls

users:
  - username: admin
    password: admin  
    role: Admin

workers:
  persistence:
    enabled: true  # Включаємо персистентне зберігання логів
    size: 10Gi  # Встановлюємо розмір для сховища логів
  env:
    - name: AIRFLOW__LOGGING__BASE_LOG_FOLDER
      value: /opt/airflow/logs  # Вказуємо шлях для збереження логів
  extraVolumeMounts:
    - name: data-storage
      mountPath: /opt/airflow/storage
  extraVolumes:
    - name: data-storage
      persistentVolumeClaim:
        claimName: data-storage-pvc

persistence:
  dataStorage:
    enabled: true
    existingClaim: ""
    storageClass: "standard"  # Замініть на ваш клас сховища
    accessMode: ReadWriteMany
    size: 10Gi
    annotations: {}
    labels: {}
    
airflow:
  extraPipPackages:
    - reportlab==3.6.12
