executor: CeleryExecutor

redis:
  enabled: true

flower:
  enabled: true

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/CtrlPy/airflow-kubernetes-example.git"
    branch: "main"
    wait: 20  # Synchronization interval in seconds

webserver:
  service:
    type: ClusterIP  # We use ClusterIP because we will use Ingress

ingress:
  enabled: true
  web:
    hosts:
      - airflow.local
    annotations:
      kubernetes.io/ingress.class: traefik
  flower:
    hosts:
      - flower.airflow.local
    annotations:
      kubernetes.io/ingress.class: traefik

  # If using TLS, uncomment and configure the following block
  # tls:
  #   - hosts:
  #       - airflow.local
  #     secretName: airflow-tls

users:
  - username: admin
    password: admin  
    role: Admin
